# Generated by Django 3.2.12 on 2022-07-14 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='وضعیت نویسندگی'),
        ),
        migrations.AddField(
            model_name='user',
            name='special_subscription',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='اشتراک ویژه'),
        ),
    ]
