version: "3.10"

services:
  app:
    container_name: 'Blog-App'
    env_file:
      - .env
    build:
      context: .
      network: host
    volumes:
      - static:/code/staticfiles/
      - media:/code/media/
    expose:
      - '8000'
    
    depends_on:
      - db
    
  nginx:
    container_name: 'Blog-Nginx'
    build: './nginx'
    ports:
      - "80:80"
    volumes:
      - static:/volumes/staticfiles/
      - media:/volumes/media/
    depends_on:
      - app
  
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

    
volumes:
  static:
  media:
  postgres_data: