# Generated by Django 3.2.12 on 2022-07-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220707_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('p', 'منتشر شده'), ('d', 'پیش\u200cنویس'), ('i', 'در حال بررسی'), ('r', 'رد شده')], max_length=1, verbose_name='وضعیت انتشار'),
        ),
    ]
