# Generated by Django 3.2.12 on 2022-07-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='مقاله ویژه'),
        ),
    ]
