# Generated by Django 3.2.12 on 2022-07-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220721_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='posts', through='blog.PostHit', to='blog.IPAddress', verbose_name='بازدیدها'),
        ),
    ]
