# Generated by Django 3.2.20 on 2023-08-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.IntegerField(unique=True, verbose_name='جایگاه'),
        ),
    ]
